In [1]:
import numpy as np

array= np.array([0,1,2,3,4,5,6,7,8,9])
print(array[0:10])

[0 1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np
array= np.array([[1,1,1], [1,1,1],[1,1,1]])
print(array==1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np
B=np.arange(1,11,2)
print(B)

In [4]:
B=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(B)
for i in B:
    if i%2==1:
        (B[i]) = -1
print(B)
D=np.where(B%2==1,-1,B)
print(D)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [5]:
C=np.array([1,2,3,4,5,6,7,8,9,10])
print(C)
A=C.reshape(2,5)
print(A)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
a=np.array([2,3,4])
b=np.array([32,33,34])
W= np.vstack((a,b))
d=np.dot(a,b)
s=np.sum(d)
print(W)
print(d)
print(s)

[[ 2  3  4]
 [32 33 34]]
299
299


In [7]:
a1=np.array([[23,34,45],[12,32,43]])
b1=np.array([[21,22],[2,3],[2,1]])
d1=np.dot(a1,b1)
s1=np.sum(d1)
s2=np.sum(b1)
print(d1)
print(s1)
print(s2)

[[641 653]
 [402 403]]
2099
51
